### ISSUE TITLE
cargo run error

### ISSUE THREAD

**Issue by cymqqqq** [radu-matei/wasi-tensorflow-inference#2]
When I run "cargo run --release", errors comes:
error: failed to run custom build command for `wasi-tensorflow-inference v0.1.0 (D:\wasi-tensorflow-inference)`

Caused by:
  process didn't exit successfully: `D:\wasi-tensorflow-inference\target\release\build\wasi-tensorflow-inference-bfccc60f65b234eb\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=crates/wasi-mobilenet-inference/src/lib.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "system can not find the file specified。" }', build.rs:17:18
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
How can I fix it?

**Comment by radu-matei** [comment]
You should install [`wasm-opt`](https://github.com/WebAssembly/binaryen) and add it to your path.

If you don't want to rebuild the model module, you can comment the `build.rs` file and use the pre-built modules that are part of the repository.
